/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/apartment.glb -o src/models/Apartment.tsx -t -k 
Author: ATD-London (https://sketchfab.com/ATD-London)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/st-edward-190-strand-apartment-layout-73b37298f69146e8a41b62e51d80b524
Title: St Edward: 190 Strand - Apartment Layout
*/

/* eslint-disable @typescript-eslint/no-unused-vars */
import * as THREE from 'three';
import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFPSControllerFromModel } from '../three/fpsController';

type GLTFAction = unknown;
type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_43: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_45: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_47: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_49: THREE.Mesh;
    Object_50: THREE.Mesh;
    Object_51: THREE.Mesh;
    Object_52: THREE.Mesh;
    Object_53: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_55: THREE.Mesh;
    Object_56: THREE.Mesh;
    Object_57: THREE.Mesh;
    Object_58: THREE.Mesh;
    Object_59: THREE.Mesh;
    Object_60: THREE.Mesh;
    Object_61: THREE.Mesh;
    Object_62: THREE.Mesh;
    Object_63: THREE.Mesh;
    Object_64: THREE.Mesh;
    Object_65: THREE.Mesh;
    Object_66: THREE.Mesh;
    Object_67: THREE.Mesh;
    Object_68: THREE.Mesh;
    Object_69: THREE.Mesh;
    Object_70: THREE.Mesh;
    Object_71: THREE.Mesh;
    Object_72: THREE.Mesh;
  };
  materials: {
    Aluminium: THREE.MeshStandardMaterial;
    Brick_Common: THREE.MeshStandardMaterial;
    Brick_Common_Yellow: THREE.MeshStandardMaterial;
    CHROME: THREE.MeshStandardMaterial;
    Cabinets: THREE.MeshStandardMaterial;
    ['Cabinets_-_Handles']: THREE.MeshStandardMaterial;
    ['Cabinets_-_PanelGlass']: THREE.MeshStandardMaterial;
    Concrete_Cast_In_Situ: THREE.MeshStandardMaterial;
    Concrete_Precast: THREE.MeshStandardMaterial;
    Dark_Brown: THREE.MeshStandardMaterial;
    Default_Wall: THREE.MeshStandardMaterial;
    ['Door_-_Architrave']: THREE.MeshStandardMaterial;
    ['Door_-_FrameMullion']: THREE.MeshStandardMaterial;
    ['Door_-_Handle']: THREE.MeshStandardMaterial;
    ['Door_-_Panel']: THREE.MeshStandardMaterial;
    ['Fabric_-_Allermuir_-_Silcoates']: THREE.MeshStandardMaterial;
    ['Fabric_-_Green']: THREE.MeshStandardMaterial;
    ['Fabric_-_Leather_Brown']: THREE.MeshStandardMaterial;
    Furniture: THREE.MeshStandardMaterial;
    Glass: THREE.MeshStandardMaterial;
    Glass_Clear_Glazing: THREE.MeshStandardMaterial;
    Glass_Clear_Glazing_Tempered: THREE.MeshStandardMaterial;
    ['Glass_-_Clear_Grey']: THREE.MeshStandardMaterial;
    Gypsum_Wall_Board: THREE.MeshStandardMaterial;
    ['Laminate_-_Ivory_Matte']: THREE.MeshStandardMaterial;
    ['Laminate_Finish_-_Kimball_Office_-_Prior']: THREE.MeshStandardMaterial;
    ['Leather_-_Allermuir_-_Fabric_-_Leather_-']: THREE.MeshStandardMaterial;
    ['Leather_-_Dark_Brown']: THREE.MeshStandardMaterial;
    Marble: THREE.MeshStandardMaterial;
    Metal_Sheeting_Rails1: THREE.MeshStandardMaterial;
    ['Metal_-_Allermuir_-_Polished_Aluminum']: THREE.MeshStandardMaterial;
    ['Metal_-_Allermuir_-_Silver']: THREE.MeshStandardMaterial;
    ['Metal_-_Chrome']: THREE.MeshStandardMaterial;
    ['Metal_-_Chrome_Polished']: THREE.MeshStandardMaterial;
    ['Metal_-_Paint_Finish_-_Dark_Gray_Matte']: THREE.MeshStandardMaterial;
    ['Metal_-_Paint_Finish_-_Ivory_Glossy']: THREE.MeshStandardMaterial;
    ['Metal_-_Stainless_Steel']: THREE.MeshStandardMaterial;
    ['Metal_-_Stainless_SteelPolished']: THREE.MeshStandardMaterial;
    ['Metal_-_Steel_Polished']: THREE.MeshStandardMaterial;
    Metal___Aluminium: THREE.MeshStandardMaterial;
    Mirror: THREE.MeshStandardMaterial;
    Mirror_Frame: THREE.MeshStandardMaterial;
    ['Paint_-_Kimball_Office_-_Priority_-_Soli']: THREE.MeshStandardMaterial;
    Plaster: THREE.MeshStandardMaterial;
    ['Plastic_-_Allermuir_-_Black']: THREE.MeshStandardMaterial;
    ['Plastic_-_Black']: THREE.MeshStandardMaterial;
    ['Plastic_-_Gray']: THREE.MeshStandardMaterial;
    ['Plastic_-_White']: THREE.MeshStandardMaterial;
    Plumbing_Fixtures: THREE.MeshStandardMaterial;
    Polished_Chrome: THREE.MeshStandardMaterial;
    Porcelain: THREE.MeshStandardMaterial;
    ['Porcelain_-_White']: THREE.MeshStandardMaterial;
    Railings: THREE.MeshStandardMaterial;
    Sofa_arm: THREE.MeshStandardMaterial;
    Sofa_seat: THREE.MeshStandardMaterial;
    Steel_Polished: THREE.MeshStandardMaterial;
    TOWEL: THREE.MeshStandardMaterial;
    ['Textile_-_White']: THREE.MeshStandardMaterial;
    Top_Rails: THREE.MeshStandardMaterial;
    Travertine: THREE.MeshStandardMaterial;
    ['Wax_-_Candle']: THREE.MeshStandardMaterial;
    ['White_Oak_-_Mystic_Brown']: THREE.MeshStandardMaterial;
    ['Window_-_Glass']: THREE.MeshStandardMaterial;
    Window_Frame: THREE.MeshStandardMaterial;
    Windows: THREE.MeshStandardMaterial;
    ['Wood_-_Birch']: THREE.MeshStandardMaterial;
    ['Wood_-_Walnut_Natural']: THREE.MeshStandardMaterial;
    ['Wood_-_Walnut_Dark_Brown']: THREE.MeshStandardMaterial;
    Wood_Dark_Brown: THREE.MeshStandardMaterial;
    ['chair-white_fabric']: THREE.MeshStandardMaterial;
    metal_table: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF('/apartment.glb') as GLTFResult;

  useFPSControllerFromModel(group);

  return (
    <group ref={group} scale={0.3} {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.Aluminium} />
        <mesh
          name="Object_3"
          geometry={nodes.Object_3.geometry}
          material={materials.Brick_Common}
        />
        <mesh
          name="Object_4"
          geometry={nodes.Object_4.geometry}
          material={materials.Brick_Common_Yellow}
        />
        <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.CHROME} />
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Cabinets} />
        <mesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials['Cabinets_-_Handles']}
        />
        <mesh
          name="Object_8"
          geometry={nodes.Object_8.geometry}
          material={materials['Cabinets_-_PanelGlass']}
        />
        <mesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={materials.Concrete_Cast_In_Situ}
        />
        <mesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={materials.Concrete_Precast}
        />
        <mesh
          name="Object_11"
          geometry={nodes.Object_11.geometry}
          material={materials.Dark_Brown}
        />
        <mesh
          name="Object_12"
          geometry={nodes.Object_12.geometry}
          material={materials.Default_Wall}
        />
        <mesh
          name="Object_13"
          geometry={nodes.Object_13.geometry}
          material={materials['Door_-_Architrave']}
        />
        <mesh
          name="Object_14"
          geometry={nodes.Object_14.geometry}
          material={materials['Door_-_FrameMullion']}
        />
        <mesh
          name="Object_15"
          geometry={nodes.Object_15.geometry}
          material={materials['Door_-_Handle']}
        />
        <mesh
          name="Object_16"
          geometry={nodes.Object_16.geometry}
          material={materials['Door_-_Panel']}
        />
        <mesh
          name="Object_17"
          geometry={nodes.Object_17.geometry}
          material={materials['Fabric_-_Allermuir_-_Silcoates']}
        />
        <mesh
          name="Object_18"
          geometry={nodes.Object_18.geometry}
          material={materials['Fabric_-_Green']}
        />
        <mesh
          name="Object_19"
          geometry={nodes.Object_19.geometry}
          material={materials['Fabric_-_Leather_Brown']}
        />
        <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.Furniture} />
        <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Glass} />
        <mesh
          name="Object_22"
          geometry={nodes.Object_22.geometry}
          material={materials.Glass_Clear_Glazing}
        />
        <mesh
          name="Object_23"
          geometry={nodes.Object_23.geometry}
          material={materials.Glass_Clear_Glazing_Tempered}
        />
        <mesh
          name="Object_24"
          geometry={nodes.Object_24.geometry}
          material={materials['Glass_-_Clear_Grey']}
        />
        <mesh
          name="Object_25"
          geometry={nodes.Object_25.geometry}
          material={materials.Gypsum_Wall_Board}
        />
        <mesh
          name="Object_26"
          geometry={nodes.Object_26.geometry}
          material={materials['Laminate_-_Ivory_Matte']}
        />
        <mesh
          name="Object_27"
          geometry={nodes.Object_27.geometry}
          material={materials['Laminate_Finish_-_Kimball_Office_-_Prior']}
        />
        <mesh
          name="Object_28"
          geometry={nodes.Object_28.geometry}
          material={materials['Leather_-_Allermuir_-_Fabric_-_Leather_-']}
        />
        <mesh
          name="Object_29"
          geometry={nodes.Object_29.geometry}
          material={materials['Leather_-_Dark_Brown']}
        />
        <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.Marble} />
        <mesh
          name="Object_31"
          geometry={nodes.Object_31.geometry}
          material={materials.Metal_Sheeting_Rails1}
        />
        <mesh
          name="Object_32"
          geometry={nodes.Object_32.geometry}
          material={materials['Metal_-_Allermuir_-_Polished_Aluminum']}
        />
        <mesh
          name="Object_33"
          geometry={nodes.Object_33.geometry}
          material={materials['Metal_-_Allermuir_-_Silver']}
        />
        <mesh
          name="Object_34"
          geometry={nodes.Object_34.geometry}
          material={materials['Metal_-_Chrome']}
        />
        <mesh
          name="Object_35"
          geometry={nodes.Object_35.geometry}
          material={materials['Metal_-_Chrome_Polished']}
        />
        <mesh
          name="Object_36"
          geometry={nodes.Object_36.geometry}
          material={materials['Metal_-_Paint_Finish_-_Dark_Gray_Matte']}
        />
        <mesh
          name="Object_37"
          geometry={nodes.Object_37.geometry}
          material={materials['Metal_-_Paint_Finish_-_Ivory_Glossy']}
        />
        <mesh
          name="Object_38"
          geometry={nodes.Object_38.geometry}
          material={materials['Metal_-_Stainless_Steel']}
        />
        <mesh
          name="Object_39"
          geometry={nodes.Object_39.geometry}
          material={materials['Metal_-_Stainless_SteelPolished']}
        />
        <mesh
          name="Object_40"
          geometry={nodes.Object_40.geometry}
          material={materials['Metal_-_Steel_Polished']}
        />
        <mesh
          name="Object_41"
          geometry={nodes.Object_41.geometry}
          material={materials.Metal___Aluminium}
        />
        <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.Mirror} />
        <mesh
          name="Object_43"
          geometry={nodes.Object_43.geometry}
          material={materials.Mirror_Frame}
        />
        <mesh
          name="Object_44"
          geometry={nodes.Object_44.geometry}
          material={materials['Paint_-_Kimball_Office_-_Priority_-_Soli']}
        />
        <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.Plaster} />
        <mesh
          name="Object_46"
          geometry={nodes.Object_46.geometry}
          material={materials['Plastic_-_Allermuir_-_Black']}
        />
        <mesh
          name="Object_47"
          geometry={nodes.Object_47.geometry}
          material={materials['Plastic_-_Black']}
        />
        <mesh
          name="Object_48"
          geometry={nodes.Object_48.geometry}
          material={materials['Plastic_-_Gray']}
        />
        <mesh
          name="Object_49"
          geometry={nodes.Object_49.geometry}
          material={materials['Plastic_-_White']}
        />
        <mesh
          name="Object_50"
          geometry={nodes.Object_50.geometry}
          material={materials.Plumbing_Fixtures}
        />
        <mesh
          name="Object_51"
          geometry={nodes.Object_51.geometry}
          material={materials.Polished_Chrome}
        />
        <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.Porcelain} />
        <mesh
          name="Object_53"
          geometry={nodes.Object_53.geometry}
          material={materials['Porcelain_-_White']}
        />
        <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.Railings} />
        <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.Sofa_arm} />
        <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.Sofa_seat} />
        <mesh
          name="Object_57"
          geometry={nodes.Object_57.geometry}
          material={materials.Steel_Polished}
        />
        <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.TOWEL} />
        <mesh
          name="Object_59"
          geometry={nodes.Object_59.geometry}
          material={materials['Textile_-_White']}
        />
        <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.Top_Rails} />
        <mesh
          name="Object_61"
          geometry={nodes.Object_61.geometry}
          material={materials.Travertine}
        />
        <mesh
          name="Object_62"
          geometry={nodes.Object_62.geometry}
          material={materials['Wax_-_Candle']}
        />
        <mesh
          name="Object_63"
          geometry={nodes.Object_63.geometry}
          material={materials['White_Oak_-_Mystic_Brown']}
        />
        <mesh
          name="Object_64"
          geometry={nodes.Object_64.geometry}
          material={materials['Window_-_Glass']}
        />
        <mesh
          name="Object_65"
          geometry={nodes.Object_65.geometry}
          material={materials.Window_Frame}
        />
        <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.Windows} />
        <mesh
          name="Object_67"
          geometry={nodes.Object_67.geometry}
          material={materials['Wood_-_Birch']}
        />
        <mesh
          name="Object_68"
          geometry={nodes.Object_68.geometry}
          material={materials['Wood_-_Walnut_Natural']}
        />
        <mesh
          name="Object_69"
          geometry={nodes.Object_69.geometry}
          material={materials['Wood_-_Walnut_Dark_Brown']}
        />
        <mesh
          name="Object_70"
          geometry={nodes.Object_70.geometry}
          material={materials.Wood_Dark_Brown}
        />
        <mesh
          name="Object_71"
          geometry={nodes.Object_71.geometry}
          material={materials['chair-white_fabric']}
        />
        <mesh
          name="Object_72"
          geometry={nodes.Object_72.geometry}
          material={materials.metal_table}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/apartment.glb');
