/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/apartment.glb -o src/models/Apartment.tsx -t -k 
*/

/* eslint-disable */
import * as THREE from 'three'
import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFAction = unknown
import { useFPSControllerFromModel } from '../three/fpsController'

type GLTFResult = GLTF & {
  nodes: {
    Object_10: THREE.Mesh
    Object_100: THREE.Mesh
    Object_101: THREE.Mesh
    Object_102: THREE.Mesh
    Object_103: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_2: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
    Object_29: THREE.Mesh
    Object_3: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_36: THREE.Mesh
    Object_37: THREE.Mesh
    Object_38: THREE.Mesh
    Object_39: THREE.Mesh
    Object_4: THREE.Mesh
    Object_40: THREE.Mesh
    Object_41: THREE.Mesh
    Object_42: THREE.Mesh
    Object_43: THREE.Mesh
    Object_44: THREE.Mesh
    Object_45: THREE.Mesh
    Object_46: THREE.Mesh
    Object_47: THREE.Mesh
    Object_48: THREE.Mesh
    Object_49: THREE.Mesh
    Object_5: THREE.Mesh
    Object_50: THREE.Mesh
    Object_51: THREE.Mesh
    Object_52: THREE.Mesh
    Object_53: THREE.Mesh
    Object_54: THREE.Mesh
    Object_55: THREE.Mesh
    Object_56: THREE.Mesh
    Object_57: THREE.Mesh
    Object_59: THREE.Mesh
    Object_6: THREE.Mesh
    Object_60: THREE.Mesh
    Object_61: THREE.Mesh
    Object_62: THREE.Mesh
    Object_63: THREE.Mesh
    Object_64: THREE.Mesh
    Object_65: THREE.Mesh
    Object_66: THREE.Mesh
    Object_67: THREE.Mesh
    Object_68: THREE.Mesh
    Object_69: THREE.Mesh
    Object_70: THREE.Mesh
    Object_71: THREE.Mesh
    Object_72: THREE.Mesh
    Object_73: THREE.Mesh
    Object_75: THREE.Mesh
    Object_77: THREE.Mesh
    Object_78: THREE.Mesh
    Object_79: THREE.Mesh
    Object_8: THREE.Mesh
    Object_80: THREE.Mesh
    Object_81: THREE.Mesh
    Object_82: THREE.Mesh
    Object_83: THREE.Mesh
    Object_84: THREE.Mesh
    Object_85: THREE.Mesh
    Object_86: THREE.Mesh
    Object_88: THREE.Mesh
    Object_89: THREE.Mesh
    Object_9: THREE.Mesh
    Object_90: THREE.Mesh
    Object_91: THREE.Mesh
    Object_92: THREE.Mesh
    Object_93: THREE.Mesh
    Object_94: THREE.Mesh
    Object_95: THREE.Mesh
    Object_96: THREE.Mesh
    Object_99: THREE.Mesh
  }
  materials: {
    ['20190412_192310_ovcol868686colpic12contpic00']: THREE.MeshStandardMaterial
    tex_bois_noir: THREE.MeshStandardMaterial
    tex_tissus_scan_taupe_010: THREE.MeshStandardMaterial
    vase_fleur_off___phong94: THREE.MeshStandardMaterial
    wc_005____interupteur: THREE.MeshStandardMaterial
    ['20190513-163125-cdt']: THREE.MeshStandardMaterial
    ['20190602-22020-edt_ovcolafb7bdcolpic11contpic05_Room_Entity_Mat']: THREE.MeshStandardMaterial
    ['20190602-222720-edt']: THREE.MeshStandardMaterial
    ['20190602-222818-edt']: THREE.MeshStandardMaterial
    ['20190603-181714-edt']: THREE.MeshStandardMaterial
    ['20191229-101443-gmt-6']: THREE.MeshStandardMaterial
    ['20200208-221542-est']: THREE.MeshStandardMaterial
    ['1111']: THREE.MeshStandardMaterial
    ['20200404-13435-cdt_Wall_Entity_Material']: THREE.MeshStandardMaterial
    ['20200516-204039-cdt']: THREE.MeshStandardMaterial
    ['20200519-73754-gmt-5']: THREE.MeshStandardMaterial
    ['20200609-162428-pdt']: THREE.MeshStandardMaterial
    ['20200611-20138-edt']: THREE.MeshStandardMaterial
    ['282770471']: THREE.MeshStandardMaterial
    ['51a0f68eae8251dd78ae3cd7d7cef225']: THREE.MeshStandardMaterial
    ['73b9ca0e33b2ae6d6e3d9526f2cbfdaa']: THREE.MeshStandardMaterial
    ['7803ba6308785db71103da3cec0e6345']: THREE.MeshStandardMaterial
    ['92ba161c2cdca450a269cc4648000e66']: THREE.MeshStandardMaterial
    ['1555650204616']: THREE.MeshStandardMaterial
    beige_006_Wall_Entity_Material: THREE.MeshStandardMaterial
    blanc_001_Wall_Entity_Material: THREE.MeshStandardMaterial
    bois_106: THREE.MeshStandardMaterial
    bureau_009___classeur: THREE.MeshStandardMaterial
    bureau_009___clavier: THREE.MeshStandardMaterial
    bureau_009___crayon: THREE.MeshStandardMaterial
    douche_italienne_001____douche_italienne_001douche_italienne_00: THREE.MeshStandardMaterial
    enduit_004_Room_Entity_Material: THREE.MeshStandardMaterial
    enduit_004_Wall_Entity_Material: THREE.MeshStandardMaterial
    fake_mat_0_0_0_255: THREE.MeshStandardMaterial
    ['20171029_191052']: THREE.MeshStandardMaterial
    fake_mat_107_107_107_255: THREE.MeshStandardMaterial
    fake_mat_152_147_143_255: THREE.MeshStandardMaterial
    fake_mat_196_192_187_255: THREE.MeshStandardMaterial
    fake_mat_210_170_106_255: THREE.MeshStandardMaterial
    fake_mat_221_221_221_255: THREE.MeshStandardMaterial
    fake_mat_227_221_202_255: THREE.MeshStandardMaterial
    fake_mat_233_237_229_255: THREE.MeshStandardMaterial
    fake_mat_254_254_254_255: THREE.MeshStandardMaterial
    ['20180331-9228-edt_Wall_Entity_Material']: THREE.MeshStandardMaterial
    fake_mat_255_255_255_32: THREE.MeshStandardMaterial
    fake_mat_26_55_74_255: THREE.MeshStandardMaterial
    fake_mat_2_2_2_255: THREE.MeshStandardMaterial
    fake_mat_32_32_32_255: THREE.MeshStandardMaterial
    fake_mat_36_36_39_255: THREE.MeshStandardMaterial
    fake_mat_48_44_43_255: THREE.MeshStandardMaterial
    fake_mat_59_59_59_255: THREE.MeshStandardMaterial
    gris_001_Wall_Entity_Material: THREE.MeshStandardMaterial
    ['20180805-17154-mdt']: THREE.MeshStandardMaterial
    gris_002_Wall_Entity_Material: THREE.MeshStandardMaterial
    ['images-2']: THREE.MeshStandardMaterial
    ['images-2_Room_Entity_Material']: THREE.MeshStandardMaterial
    kitchen_classic_style_base_cabinet_oven_002___lambert8sg: THREE.MeshStandardMaterial
    kitchen_classic_style_tall_cabinet_oven_004___mat_oven002sg: THREE.MeshStandardMaterial
    kitchen_classic_style_tall_cabinet_oven_004___mat_oven005sg: THREE.MeshStandardMaterial
    kitchen_classic_style_tall_cabinet_oven_004___mat_stainless_bru: THREE.MeshStandardMaterial
    lit_012___mat_tissus057sg: THREE.MeshStandardMaterial
    marron_004_Wall_Entity_Material: THREE.MeshStandardMaterial
    metal_012: THREE.MeshStandardMaterial
    meuble_lavabo_006____meuble_lavabo_00511___default: THREE.MeshStandardMaterial
    meuble_lavabo_006____meuble_lavabo_005metal: THREE.MeshStandardMaterial
    orange_004_ovcolbdb2afcolpic04contpic05_Wall_Entity_Material: THREE.MeshStandardMaterial
    orange_004_ovcolc5aea7colpic04contpic04_Wall_Entity_Material: THREE.MeshStandardMaterial
    pack_003_salon_plante___material__142: THREE.MeshStandardMaterial
    pack_003_salon_television___material__80_1: THREE.MeshStandardMaterial
    pack_003_salon_television___material__81: THREE.MeshStandardMaterial
    pack_005_salle_de_sport_etagere___nopaint_livre001: THREE.MeshStandardMaterial
    ['20180916-143440-pdt']: THREE.MeshStandardMaterial
    pack_005_salle_de_sport_etagere___nopaint_livre002: THREE.MeshStandardMaterial
    pack_005_salle_de_sport_etagere___nopaint_livre003: THREE.MeshStandardMaterial
    pack_005_salle_de_sport_etagere___nopaint_livre004: THREE.MeshStandardMaterial
    pack_005_salle_de_sport_etagere___panier: THREE.MeshStandardMaterial
    pack_005_salle_de_sport_etagere___serviettes001: THREE.MeshStandardMaterial
    pack_005_salle_de_sport_etagere___serviettes002: THREE.MeshStandardMaterial
    pack_005_salle_de_sport_etagere___serviettes003: THREE.MeshStandardMaterial
    plante_vase_off_002___phong19: THREE.MeshStandardMaterial
    plante_vase_off_002___phong38: THREE.MeshStandardMaterial
    ['20180916-143440-pdt_Room_Entity_Material']: THREE.MeshStandardMaterial
    radio_ww___phong334: THREE.MeshStandardMaterial
    radio_ww___phong335: THREE.MeshStandardMaterial
    refrigerateur_006____refrigerateur_006_refrigerateur_006_refrig: THREE.MeshStandardMaterial
    refrigerateur_006____refrigerateur_006_refrigerateur_006_re: THREE.MeshStandardMaterial
    ['refrigerateur_006____refrigerateur_006_refrigerateur_006_re.001']: THREE.MeshStandardMaterial
    rideaux_003___rideaux_003lambert2sg: THREE.MeshStandardMaterial
    seche_linge_003___ecran: THREE.MeshStandardMaterial
    table_multi_usage_off___gris1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/apartment.glb') as GLTFResult
  const group = useRef<THREE.Group>(null)
  useFPSControllerFromModel(group)
  useEffect(() => {
    const root = group.current
    if (!root) return
    root.traverse((o) => {
      const m = o as THREE.Mesh
      if ((m as any).isMesh) {
        m.castShadow = true
        m.receiveShadow = true
      }
    })
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_model" position={[3.907, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['20190412_192310_ovcol868686colpic12contpic00']} />
        <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.tex_bois_noir} />
        <mesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials.tex_tissus_scan_taupe_010} />
        <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.vase_fleur_off___phong94} />
        <mesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.wc_005____interupteur} />
        <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['20190513-163125-cdt']} />
        <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['20190602-22020-edt_ovcolafb7bdcolpic11contpic05_Room_Entity_Mat']} />
        <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['20190602-222720-edt']} />
        <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['20190602-222818-edt']} />
        <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials['20190603-181714-edt']} />
        <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials['20191229-101443-gmt-6']} />
        <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['20200208-221542-est']} />
        <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials['1111']} />
        <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials['20200404-13435-cdt_Wall_Entity_Material']} />
        <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials['20200516-204039-cdt']} />
        <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials['20200519-73754-gmt-5']} />
        <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials['20200609-162428-pdt']} />
        <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['20200611-20138-edt']} />
        <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials['282770471']} />
        <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['51a0f68eae8251dd78ae3cd7d7cef225']} />
        <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials['73b9ca0e33b2ae6d6e3d9526f2cbfdaa']} />
        <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials['7803ba6308785db71103da3cec0e6345']} />
        <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials['92ba161c2cdca450a269cc4648000e66']} />
        <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials['1555650204616']} />
        <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.beige_006_Wall_Entity_Material} />
        <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.blanc_001_Wall_Entity_Material} />
        <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.bois_106} />
        <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.bureau_009___classeur} />
        <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.bureau_009___clavier} />
        <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.bureau_009___crayon} />
        <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.douche_italienne_001____douche_italienne_001douche_italienne_00} />
        <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.enduit_004_Room_Entity_Material} />
        <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.enduit_004_Wall_Entity_Material} />
        <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.fake_mat_0_0_0_255} />
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['20171029_191052']} />
        <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.fake_mat_0_0_0_255} />
        <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.fake_mat_107_107_107_255} />
        <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.fake_mat_152_147_143_255} />
        <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.fake_mat_196_192_187_255} />
        <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.fake_mat_210_170_106_255} />
        <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.fake_mat_221_221_221_255} />
        <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.fake_mat_227_221_202_255} />
        <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.fake_mat_227_221_202_255} />
        <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.fake_mat_233_237_229_255} />
        <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.fake_mat_254_254_254_255} />
        <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['20180331-9228-edt_Wall_Entity_Material']} />
        <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.fake_mat_255_255_255_32} />
        <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.fake_mat_26_55_74_255} />
        <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.fake_mat_2_2_2_255} />
        <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.fake_mat_32_32_32_255} />
        <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.fake_mat_36_36_39_255} />
        <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.fake_mat_48_44_43_255} />
        <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.fake_mat_48_44_43_255} />
        <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.fake_mat_59_59_59_255} />
        <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.gris_001_Wall_Entity_Material} />
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['20180805-17154-mdt']} />
        <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.gris_002_Wall_Entity_Material} />
        <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials['images-2']} />
        <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials['images-2_Room_Entity_Material']} />
        <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.kitchen_classic_style_base_cabinet_oven_002___lambert8sg} />
        <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.kitchen_classic_style_tall_cabinet_oven_004___mat_oven002sg} />
        <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.kitchen_classic_style_tall_cabinet_oven_004___mat_oven005sg} />
        <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.kitchen_classic_style_tall_cabinet_oven_004___mat_stainless_bru} />
        <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.lit_012___mat_tissus057sg} />
        <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.marron_004_Wall_Entity_Material} />
        <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.metal_012} />
        <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.meuble_lavabo_006____meuble_lavabo_00511___default} />
        <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.meuble_lavabo_006____meuble_lavabo_005metal} />
        <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.orange_004_ovcolbdb2afcolpic04contpic05_Wall_Entity_Material} />
        <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.orange_004_ovcolc5aea7colpic04contpic04_Wall_Entity_Material} />
        <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.pack_003_salon_plante___material__142} />
        <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.pack_003_salon_television___material__80_1} />
        <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.pack_003_salon_television___material__81} />
        <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.pack_005_salle_de_sport_etagere___nopaint_livre001} />
        <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['20180916-143440-pdt']} />
        <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.pack_005_salle_de_sport_etagere___nopaint_livre002} />
        <mesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.pack_005_salle_de_sport_etagere___nopaint_livre003} />
        <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.pack_005_salle_de_sport_etagere___nopaint_livre004} />
        <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.pack_005_salle_de_sport_etagere___panier} />
        <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.pack_005_salle_de_sport_etagere___serviettes001} />
        <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.pack_005_salle_de_sport_etagere___serviettes002} />
        <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.pack_005_salle_de_sport_etagere___serviettes003} />
        <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.plante_vase_off_002___phong19} />
        <mesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials.plante_vase_off_002___phong38} />
        <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['20180916-143440-pdt_Room_Entity_Material']} />
        <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.radio_ww___phong334} />
        <mesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.radio_ww___phong335} />
        <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.refrigerateur_006____refrigerateur_006_refrigerateur_006_refrig} />
        <mesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.refrigerateur_006____refrigerateur_006_refrigerateur_006_re} />
        <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials['refrigerateur_006____refrigerateur_006_refrigerateur_006_re.001']} />
        <mesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.rideaux_003___rideaux_003lambert2sg} />
        <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.seche_linge_003___ecran} />
        <mesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.table_multi_usage_off___gris1} />
      </group>
    </group>
  )
}

useGLTF.preload('/apartment.glb')
