/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/room_apartment_furniture.glb -o src/models/RoomApartment.tsx -t -k 
Author: yuuuusukeeee (https://sketchfab.com/yuuuusukeeee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/room-apartment-furniture-1b5e5528de8f4b65a0eac856317c71f6
Title: Room_[apartment_furniture]
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFAction = unknown;

type GLTFResult = GLTF & {
  nodes: {
    Object_8: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_49: THREE.Mesh;
    Object_51: THREE.Mesh;
    Object_53: THREE.Mesh;
    Object_55: THREE.Mesh;
    Object_57: THREE.Mesh;
    Object_59: THREE.Mesh;
    Object_61: THREE.Mesh;
    Object_63: THREE.Mesh;
    Object_65: THREE.Mesh;
    Object_67: THREE.Mesh;
    Object_69: THREE.Mesh;
    Object_71: THREE.Mesh;
    Object_73: THREE.Mesh;
    Object_75: THREE.Mesh;
    Object_77: THREE.Mesh;
    Object_79: THREE.Mesh;
    Object_81: THREE.Mesh;
    Object_83: THREE.Mesh;
    Object_85: THREE.Mesh;
    Object_87: THREE.Mesh;
    Object_89: THREE.Mesh;
    Object_91: THREE.Mesh;
    Object_93: THREE.Mesh;
    Object_95: THREE.Mesh;
    Object_98: THREE.Mesh;
    Object_100: THREE.Mesh;
    Object_103: THREE.Mesh;
    Object_105: THREE.Mesh;
    Object_107: THREE.Mesh;
    Object_109: THREE.Mesh;
    Object_111: THREE.Mesh;
    Object_113: THREE.Mesh;
    Object_115: THREE.Mesh;
    Object_117: THREE.Mesh;
    Object_119: THREE.Mesh;
    Object_121: THREE.Mesh;
    Object_123: THREE.Mesh;
    Object_125: THREE.Mesh;
    Object_127: THREE.Mesh;
    Object_129: THREE.Mesh;
    Object_131: THREE.Mesh;
    Object_133: THREE.Mesh;
    Object_135: THREE.Mesh;
    Object_137: THREE.Mesh;
    Object_139: THREE.Mesh;
    Object_142: THREE.Mesh;
    Object_144: THREE.Mesh;
    Object_146: THREE.Mesh;
    Object_148: THREE.Mesh;
    Object_150: THREE.Mesh;
    Object_152: THREE.Mesh;
    Object_154: THREE.Mesh;
    Object_156: THREE.Mesh;
    Object_158: THREE.Mesh;
    Object_160: THREE.Mesh;
    Object_163: THREE.Mesh;
    Object_165: THREE.Mesh;
    Object_167: THREE.Mesh;
    Object_169: THREE.Mesh;
    Object_171: THREE.Mesh;
    Object_173: THREE.Mesh;
    Object_175: THREE.Mesh;
    Object_177: THREE.Mesh;
    Object_179: THREE.Mesh;
    Object_181: THREE.Mesh;
    Object_183: THREE.Mesh;
    Object_185: THREE.Mesh;
    Object_187: THREE.Mesh;
    Object_189: THREE.Mesh;
    Object_191: THREE.Mesh;
    Object_193: THREE.Mesh;
    Object_195: THREE.Mesh;
    Object_197: THREE.Mesh;
    Object_199: THREE.Mesh;
    Object_201: THREE.Mesh;
    Object_203: THREE.Mesh;
    Object_205: THREE.Mesh;
    Object_207: THREE.Mesh;
    Object_209: THREE.Mesh;
    Object_213: THREE.Mesh;
    Object_215: THREE.Mesh;
    Object_217: THREE.Mesh;
    Object_219: THREE.Mesh;
    Object_221: THREE.Mesh;
    Object_223: THREE.Mesh;
    Object_225: THREE.Mesh;
    Object_227: THREE.Mesh;
    Object_229: THREE.Mesh;
    Object_231: THREE.Mesh;
    Object_233: THREE.Mesh;
    Object_236: THREE.Mesh;
    Object_239: THREE.Mesh;
    Object_242: THREE.Mesh;
    Object_244: THREE.Mesh;
    Object_246: THREE.Mesh;
    Object_248: THREE.Mesh;
    Object_250: THREE.Mesh;
    Object_252: THREE.Mesh;
    Object_254: THREE.Mesh;
    Object_256: THREE.Mesh;
    Object_258: THREE.Mesh;
    Object_260: THREE.Mesh;
    Object_262: THREE.Mesh;
    Object_264: THREE.Mesh;
    Object_266: THREE.Mesh;
    Object_268: THREE.Mesh;
    Object_270: THREE.Mesh;
    Object_272: THREE.Mesh;
    Object_274: THREE.Mesh;
    Object_276: THREE.Mesh;
    Object_278: THREE.Mesh;
    Object_280: THREE.Mesh;
    Object_282: THREE.Mesh;
    Object_284: THREE.Mesh;
    Object_286: THREE.Mesh;
    Object_288: THREE.Mesh;
    Object_290: THREE.Mesh;
    Object_292: THREE.Mesh;
    Object_295: THREE.Mesh;
    Object_297: THREE.Mesh;
    Object_299: THREE.Mesh;
    Object_304: THREE.Mesh;
    Object_307: THREE.Mesh;
    Object_309: THREE.Mesh;
    Object_311: THREE.Mesh;
    Object_313: THREE.Mesh;
    Object_316: THREE.Mesh;
    Object_318: THREE.Mesh;
    Object_321: THREE.Mesh;
    Object_324: THREE.Mesh;
    Object_326: THREE.Mesh;
    Object_330: THREE.Mesh;
    Object_332: THREE.Mesh;
    Object_335: THREE.Mesh;
    Object_338: THREE.Mesh;
    Object_340: THREE.Mesh;
    Object_343: THREE.Mesh;
    Object_346: THREE.Mesh;
    Object_348: THREE.Mesh;
    Object_350: THREE.Mesh;
    Object_352: THREE.Mesh;
    Object_354: THREE.Mesh;
    Object_356: THREE.Mesh;
    Object_358: THREE.Mesh;
    Object_360: THREE.Mesh;
    Object_362: THREE.Mesh;
    Object_364: THREE.Mesh;
    Object_366: THREE.Mesh;
    Object_368: THREE.Mesh;
    Object_370: THREE.Mesh;
    Object_372: THREE.Mesh;
    Object_374: THREE.Mesh;
    Object_376: THREE.Mesh;
    Object_378: THREE.Mesh;
    Object_380: THREE.Mesh;
    Object_382: THREE.Mesh;
    Object_384: THREE.Mesh;
    Object_386: THREE.Mesh;
    Object_390: THREE.Mesh;
    Object_392: THREE.Mesh;
    Object_395: THREE.Mesh;
    Object_397: THREE.Mesh;
    Object_399: THREE.Mesh;
    Object_401: THREE.Mesh;
    Object_403: THREE.Mesh;
    Object_406: THREE.Mesh;
    Object_408: THREE.Mesh;
    Object_410: THREE.Mesh;
    Object_412: THREE.Mesh;
    Object_414: THREE.Mesh;
    Object_416: THREE.Mesh;
    Object_418: THREE.Mesh;
    Object_421: THREE.Mesh;
    Object_423: THREE.Mesh;
    Object_425: THREE.Mesh;
    Object_427: THREE.Mesh;
    Object_430: THREE.Mesh;
    Object_432: THREE.Mesh;
    Object_435: THREE.Mesh;
    Object_437: THREE.Mesh;
    Object_439: THREE.Mesh;
    Object_441: THREE.Mesh;
    Object_443: THREE.Mesh;
    Object_445: THREE.Mesh;
    Object_447: THREE.Mesh;
  };
  materials: {
    ['color-black']: THREE.MeshStandardMaterial;
    ['color-brown2']: THREE.MeshStandardMaterial;
    ['color-grey']: THREE.MeshStandardMaterial;
    ['color-white']: THREE.MeshStandardMaterial;
    metal: THREE.MeshStandardMaterial;
    mirror: THREE.MeshStandardMaterial;
    ['color-brown']: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/room_apartment_furniture.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Items_New_156" scale={0.001}>
        <mesh
          name="Object_8"
          geometry={nodes.Object_8.geometry}
          material={materials['color-black']}
        />
        <mesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={materials['color-black']}
        />
        <mesh
          name="Object_13"
          geometry={nodes.Object_13.geometry}
          material={materials['color-brown2']}
        />
        <mesh
          name="Object_15"
          geometry={nodes.Object_15.geometry}
          material={materials['color-brown2']}
        />
        <mesh
          name="Object_17"
          geometry={nodes.Object_17.geometry}
          material={materials['color-brown2']}
        />
        <mesh
          name="Object_19"
          geometry={nodes.Object_19.geometry}
          material={materials['color-brown2']}
        />
        <mesh
          name="Object_21"
          geometry={nodes.Object_21.geometry}
          material={materials['color-brown2']}
        />
        <mesh
          name="Object_24"
          geometry={nodes.Object_24.geometry}
          material={materials['color-grey']}
        />
        <mesh
          name="Object_26"
          geometry={nodes.Object_26.geometry}
          material={materials['color-grey']}
        />
        <mesh
          name="Object_28"
          geometry={nodes.Object_28.geometry}
          material={materials['color-grey']}
        />
        <mesh
          name="Object_30"
          geometry={nodes.Object_30.geometry}
          material={materials['color-grey']}
        />
        <mesh
          name="Object_32"
          geometry={nodes.Object_32.geometry}
          material={materials['color-grey']}
        />
        <mesh
          name="Object_34"
          geometry={nodes.Object_34.geometry}
          material={materials['color-grey']}
        />
        <mesh
          name="Object_36"
          geometry={nodes.Object_36.geometry}
          material={materials['color-grey']}
        />
        <mesh
          name="Object_38"
          geometry={nodes.Object_38.geometry}
          material={materials['color-grey']}
        />
        <mesh
          name="Object_40"
          geometry={nodes.Object_40.geometry}
          material={materials['color-grey']}
        />
        <mesh
          name="Object_42"
          geometry={nodes.Object_42.geometry}
          material={materials['color-grey']}
        />
        <mesh
          name="Object_44"
          geometry={nodes.Object_44.geometry}
          material={materials['color-grey']}
        />
        <mesh
          name="Object_46"
          geometry={nodes.Object_46.geometry}
          material={materials['color-grey']}
        />
        <mesh
          name="Object_49"
          geometry={nodes.Object_49.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_51"
          geometry={nodes.Object_51.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_53"
          geometry={nodes.Object_53.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_55"
          geometry={nodes.Object_55.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_57"
          geometry={nodes.Object_57.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_59"
          geometry={nodes.Object_59.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_61"
          geometry={nodes.Object_61.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_63"
          geometry={nodes.Object_63.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_65"
          geometry={nodes.Object_65.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_67"
          geometry={nodes.Object_67.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_69"
          geometry={nodes.Object_69.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_71"
          geometry={nodes.Object_71.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_73"
          geometry={nodes.Object_73.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_75"
          geometry={nodes.Object_75.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_77"
          geometry={nodes.Object_77.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_79"
          geometry={nodes.Object_79.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_81"
          geometry={nodes.Object_81.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_83"
          geometry={nodes.Object_83.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_85"
          geometry={nodes.Object_85.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_87"
          geometry={nodes.Object_87.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_89"
          geometry={nodes.Object_89.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_91"
          geometry={nodes.Object_91.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_93"
          geometry={nodes.Object_93.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_95"
          geometry={nodes.Object_95.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_98"
          geometry={nodes.Object_98.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_100"
          geometry={nodes.Object_100.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_103"
          geometry={nodes.Object_103.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_105"
          geometry={nodes.Object_105.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_107"
          geometry={nodes.Object_107.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_109"
          geometry={nodes.Object_109.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_111"
          geometry={nodes.Object_111.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_113"
          geometry={nodes.Object_113.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_115"
          geometry={nodes.Object_115.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_117"
          geometry={nodes.Object_117.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_119"
          geometry={nodes.Object_119.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_121"
          geometry={nodes.Object_121.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_123"
          geometry={nodes.Object_123.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_125"
          geometry={nodes.Object_125.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_127"
          geometry={nodes.Object_127.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_129"
          geometry={nodes.Object_129.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_131"
          geometry={nodes.Object_131.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_133"
          geometry={nodes.Object_133.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_135"
          geometry={nodes.Object_135.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_137"
          geometry={nodes.Object_137.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_139"
          geometry={nodes.Object_139.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_142"
          geometry={nodes.Object_142.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_144"
          geometry={nodes.Object_144.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_146"
          geometry={nodes.Object_146.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_148"
          geometry={nodes.Object_148.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_150"
          geometry={nodes.Object_150.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_152"
          geometry={nodes.Object_152.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_154"
          geometry={nodes.Object_154.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_156"
          geometry={nodes.Object_156.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_158"
          geometry={nodes.Object_158.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_160"
          geometry={nodes.Object_160.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_163"
          geometry={nodes.Object_163.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_165"
          geometry={nodes.Object_165.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_167"
          geometry={nodes.Object_167.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_169"
          geometry={nodes.Object_169.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_171"
          geometry={nodes.Object_171.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_173"
          geometry={nodes.Object_173.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_175"
          geometry={nodes.Object_175.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_177"
          geometry={nodes.Object_177.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_179"
          geometry={nodes.Object_179.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_181"
          geometry={nodes.Object_181.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_183"
          geometry={nodes.Object_183.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_185"
          geometry={nodes.Object_185.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_187"
          geometry={nodes.Object_187.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_189"
          geometry={nodes.Object_189.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_191"
          geometry={nodes.Object_191.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_193"
          geometry={nodes.Object_193.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_195"
          geometry={nodes.Object_195.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_197"
          geometry={nodes.Object_197.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_199"
          geometry={nodes.Object_199.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_201"
          geometry={nodes.Object_201.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_203"
          geometry={nodes.Object_203.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_205"
          geometry={nodes.Object_205.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_207"
          geometry={nodes.Object_207.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_209"
          geometry={nodes.Object_209.geometry}
          material={materials['color-white']}
        />
        <mesh name="Object_213" geometry={nodes.Object_213.geometry} material={materials.metal} />
        <mesh name="Object_215" geometry={nodes.Object_215.geometry} material={materials.metal} />
        <mesh name="Object_217" geometry={nodes.Object_217.geometry} material={materials.metal} />
        <mesh name="Object_219" geometry={nodes.Object_219.geometry} material={materials.metal} />
        <mesh name="Object_221" geometry={nodes.Object_221.geometry} material={materials.metal} />
        <mesh name="Object_223" geometry={nodes.Object_223.geometry} material={materials.metal} />
        <mesh name="Object_225" geometry={nodes.Object_225.geometry} material={materials.metal} />
        <mesh name="Object_227" geometry={nodes.Object_227.geometry} material={materials.metal} />
        <mesh name="Object_229" geometry={nodes.Object_229.geometry} material={materials.metal} />
        <mesh name="Object_231" geometry={nodes.Object_231.geometry} material={materials.metal} />
        <mesh name="Object_233" geometry={nodes.Object_233.geometry} material={materials.metal} />
        <mesh name="Object_236" geometry={nodes.Object_236.geometry} material={materials.metal} />
        <mesh name="Object_239" geometry={nodes.Object_239.geometry} material={materials.metal} />
        <mesh name="Object_242" geometry={nodes.Object_242.geometry} material={materials.metal} />
        <mesh name="Object_244" geometry={nodes.Object_244.geometry} material={materials.metal} />
        <mesh name="Object_246" geometry={nodes.Object_246.geometry} material={materials.metal} />
        <mesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials.metal} />
        <mesh name="Object_250" geometry={nodes.Object_250.geometry} material={materials.metal} />
        <mesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials.metal} />
        <mesh name="Object_254" geometry={nodes.Object_254.geometry} material={materials.metal} />
        <mesh name="Object_256" geometry={nodes.Object_256.geometry} material={materials.metal} />
        <mesh name="Object_258" geometry={nodes.Object_258.geometry} material={materials.metal} />
        <mesh name="Object_260" geometry={nodes.Object_260.geometry} material={materials.metal} />
        <mesh name="Object_262" geometry={nodes.Object_262.geometry} material={materials.metal} />
        <mesh name="Object_264" geometry={nodes.Object_264.geometry} material={materials.metal} />
        <mesh name="Object_266" geometry={nodes.Object_266.geometry} material={materials.metal} />
        <mesh name="Object_268" geometry={nodes.Object_268.geometry} material={materials.metal} />
        <mesh name="Object_270" geometry={nodes.Object_270.geometry} material={materials.metal} />
        <mesh name="Object_272" geometry={nodes.Object_272.geometry} material={materials.metal} />
        <mesh name="Object_274" geometry={nodes.Object_274.geometry} material={materials.metal} />
        <mesh name="Object_276" geometry={nodes.Object_276.geometry} material={materials.metal} />
        <mesh name="Object_278" geometry={nodes.Object_278.geometry} material={materials.metal} />
        <mesh name="Object_280" geometry={nodes.Object_280.geometry} material={materials.metal} />
        <mesh name="Object_282" geometry={nodes.Object_282.geometry} material={materials.metal} />
        <mesh name="Object_284" geometry={nodes.Object_284.geometry} material={materials.metal} />
        <mesh name="Object_286" geometry={nodes.Object_286.geometry} material={materials.metal} />
        <mesh name="Object_288" geometry={nodes.Object_288.geometry} material={materials.metal} />
        <mesh name="Object_290" geometry={nodes.Object_290.geometry} material={materials.metal} />
        <mesh name="Object_292" geometry={nodes.Object_292.geometry} material={materials.metal} />
        <mesh name="Object_295" geometry={nodes.Object_295.geometry} material={materials.mirror} />
        <mesh name="Object_297" geometry={nodes.Object_297.geometry} material={materials.mirror} />
        <mesh name="Object_299" geometry={nodes.Object_299.geometry} material={materials.mirror} />
      </group>
      <group name="ArchitectureNew_240" scale={0.001}>
        <mesh
          name="Object_304"
          geometry={nodes.Object_304.geometry}
          material={materials['color-brown']}
        />
        <mesh
          name="Object_307"
          geometry={nodes.Object_307.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_309"
          geometry={nodes.Object_309.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_311"
          geometry={nodes.Object_311.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_313"
          geometry={nodes.Object_313.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_316"
          geometry={nodes.Object_316.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_318"
          geometry={nodes.Object_318.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_321"
          geometry={nodes.Object_321.geometry}
          material={materials['color-grey']}
        />
        <mesh
          name="Object_324"
          geometry={nodes.Object_324.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_326"
          geometry={nodes.Object_326.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_330"
          geometry={nodes.Object_330.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_332"
          geometry={nodes.Object_332.geometry}
          material={materials['color-white']}
        />
        <mesh name="Object_335" geometry={nodes.Object_335.geometry} material={materials.metal} />
        <mesh
          name="Object_338"
          geometry={nodes.Object_338.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_340"
          geometry={nodes.Object_340.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_343"
          geometry={nodes.Object_343.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_346"
          geometry={nodes.Object_346.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_348"
          geometry={nodes.Object_348.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_350"
          geometry={nodes.Object_350.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_352"
          geometry={nodes.Object_352.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_354"
          geometry={nodes.Object_354.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_356"
          geometry={nodes.Object_356.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_358"
          geometry={nodes.Object_358.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_360"
          geometry={nodes.Object_360.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_362"
          geometry={nodes.Object_362.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_364"
          geometry={nodes.Object_364.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_366"
          geometry={nodes.Object_366.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_368"
          geometry={nodes.Object_368.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_370"
          geometry={nodes.Object_370.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_372"
          geometry={nodes.Object_372.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_374"
          geometry={nodes.Object_374.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_376"
          geometry={nodes.Object_376.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_378"
          geometry={nodes.Object_378.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_380"
          geometry={nodes.Object_380.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_382"
          geometry={nodes.Object_382.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_384"
          geometry={nodes.Object_384.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_386"
          geometry={nodes.Object_386.geometry}
          material={materials['color-white']}
        />
        <mesh name="Object_390" geometry={nodes.Object_390.geometry} material={materials.metal} />
        <mesh
          name="Object_392"
          geometry={nodes.Object_392.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_395"
          geometry={nodes.Object_395.geometry}
          material={materials.material}
        />
        <mesh
          name="Object_397"
          geometry={nodes.Object_397.geometry}
          material={materials.material}
        />
        <mesh
          name="Object_399"
          geometry={nodes.Object_399.geometry}
          material={materials.material}
        />
        <mesh
          name="Object_401"
          geometry={nodes.Object_401.geometry}
          material={materials.material}
        />
        <mesh
          name="Object_403"
          geometry={nodes.Object_403.geometry}
          material={materials.material}
        />
        <mesh name="Object_406" geometry={nodes.Object_406.geometry} material={materials.metal} />
        <mesh name="Object_408" geometry={nodes.Object_408.geometry} material={materials.metal} />
        <mesh name="Object_410" geometry={nodes.Object_410.geometry} material={materials.metal} />
        <mesh name="Object_412" geometry={nodes.Object_412.geometry} material={materials.metal} />
        <mesh name="Object_414" geometry={nodes.Object_414.geometry} material={materials.metal} />
        <mesh name="Object_416" geometry={nodes.Object_416.geometry} material={materials.metal} />
        <mesh name="Object_418" geometry={nodes.Object_418.geometry} material={materials.metal} />
        <mesh
          name="Object_421"
          geometry={nodes.Object_421.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_423"
          geometry={nodes.Object_423.geometry}
          material={materials['color-white']}
        />
        <mesh name="Object_425" geometry={nodes.Object_425.geometry} material={materials.metal} />
        <mesh name="Object_427" geometry={nodes.Object_427.geometry} material={materials.metal} />
        <mesh
          name="Object_430"
          geometry={nodes.Object_430.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_432"
          geometry={nodes.Object_432.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_435"
          geometry={nodes.Object_435.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_437"
          geometry={nodes.Object_437.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_439"
          geometry={nodes.Object_439.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_441"
          geometry={nodes.Object_441.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_443"
          geometry={nodes.Object_443.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_445"
          geometry={nodes.Object_445.geometry}
          material={materials['color-white']}
        />
        <mesh
          name="Object_447"
          geometry={nodes.Object_447.geometry}
          material={materials['color-white']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/room_apartment_furniture.glb');
